spring:
  datasource:
    password: 'password'
    url: 'jdbc:postgresql://localhost:5432/tasky'
    username: 'tasky_adm'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: false
server:
  port: 8080
  error:
    include-message: always